### ISSUE TITLE
List All Courses

### ISSUE THREAD

**Issue by YaleL** [YaleL/DailyPlanning#5]
Create epics and a list (in excel) for all courses w/ details and goals, including current status.

**Comment by zheli001** [comment]
https://docs.google.com/spreadsheets/d/1ptVpsTc7_cZHrLSgXxWyDu1d0OKKcgYuTbwjy7mQ_Uo/edit?ts=60a1a2dc#gid=0

**Comment by zheli001** [comment]
I don't see.anything here?!
